- name: install nginx
  yum: name=nginx state=present

- name: copy conf
  copy:
    src: "roles/nginx/files/{{ item.src}}"
    dest: "/etc/nginx/{{ item.dest }}"
    backup: no
    owner: root
    group: root
  loop:
    - { src: nginx.conf, dest: .}
