---
version: 2
jobs:
  build:
    docker:
      - image: particlekit/ansible-lint:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: find . -name "*.yml" | xargs -IARG yamllint -c .circleci/yamllint/config ARG
      - run: ansible-lint ./playbook/*.yml -c .circleci/.ansible-lint
    docker:
      - image: centos7:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: ansible-playbook -i playbook/hosts playbook/site.yml -D
