---
version: 2
jobs:
  build:
    docker:
      - image: particlekit/ansible-lint:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: find . -name "*.yml" | xargs -IARG yamllint -c .circleci/yamllint/config ARG
      - run: ansible-lint ./playbook/*.yml -c .circleci/.ansible-lint
