---
version: 2
jobs:
  build:
    docker:
      - image: python:2.7
    working_directory: ~/repo
    steps:
      - checkout
      - run: pip install -r ./.circleci/requirements.txt
      - run: find . -name "*.yml" | xargs -IARG yamllint -c .circleci/yamllint/config ARG
      - run: ansible-lint ./playbook/*.yml -c .circleci/.ansible-lint
